# Generated by Django 5.0.4 on 2024-12-02 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppSIT', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='group',
            constraint=models.UniqueConstraint(fields=('teacher',), name='unique_teacher_per_group'),
        ),
    ]
